### ISSUE TITLE
print_config is not recognized as a command for DRAM.py

### ISSUE THREAD

**Issue by CK7** [shafferm/DRAM#11]
I copied the command from the README and this is what I got:
$DRAM.py print_config
usage: DRAM.py [-h] {annotate,annotate_genes,distill,strainer} ...
DRAM.py: error: invalid choice: 'print_config' (choose from 'annotate', 'annotate_genes', 'distill', 'strainer')

**Comment by shafferm** [comment]
This is outdated and the READEME.md has been updated. The current command is `DRAM-setup.py print_config`.

**Comment by CK7** [comment]
Thanks, you may also want to change the same command here:
https://github.com/shafferm/DRAM/wiki/2.-How-to-Install-and-Set-Up-DRAM

**Comment by shafferm** [comment]
Updated there as well. Thanks!
