### ISSUE TITLE
No such file: GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa

### ISSUE THREAD

**Issue by franztastic** [shafferm/DRAM#111]
Hi, 
Once I run annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa
that's my output:
zsh: no such file or directory: annotation/working_dir/GF2_mjMb2B_input_S53_megahit.contigs/tmp/genes.faa

How could I fix this?

Thank you very much for your help!

**Comment by shafferm** [comment]
Responded in #102
