### ISSUE TITLE
DRAM-setup.py failed due to permission issue

### ISSUE THREAD

**Issue by CK7** [shafferm/DRAM#12]
Hello,
I executed the following command to setup the databases:

DRAM-setup.py prepare_databases --output_dir DRAM_data --kegg_loc /work/kegg/genes/fasta/prokaryotes.pep.gz

Below is the log information I got (KEGG preparation went ok). Do I have to run this with sudo permissions? I installed DRAM manually.

Thank you
Itai

21:10:16.921544: UniRef database processed
23:22:43.691280: PFAM database processed
23:24:47.117465: dbCAN database processed
23:25:35.197371: RefSeq viral database processed
23:28:28.225878: MEROPS database processed
23:32:53.580668: VOGdb database processed
23:57:56.854503: KOfam database processed
23:58:04.441551: KOfam ko list processed
23:58:05.899010: PFAM hmm dat processed
23:58:09.833122: dbCAN fam activities processed
23:58:10.359248: VOGdb annotations processed
23:58:14.626950: DRAM databases and forms downloaded
23:58:14.637867: Files moved to final destination
23:58:14.638086: Setting database paths
23:58:14.638677: Database locations added to CONFIG
23:59:05.980345: Database connection established
1 day, 0:10:49.030301: KEGG descriptions added to description database
1 day, 2:06:23.040529: UniRef descriptions added to description database
1 day, 2:06:25.913270: PFAM descriptions added to description database
1 day, 2:06:27.709516: dbCAN descriptions added to description database
1 day, 2:06:37.562016: RefSeq viral descriptions added to description database
1 day, 2:07:02.511976: MEROPS descriptions added to description database
1 day, 2:07:05.523447: VOGdb descriptions added to description database
1 day, 2:07:05.523527: Description database populated
1 day, 2:07:05.523645: Database descriptions updated
Traceback (most recent call last):
  File "/usr/local/bin/DRAM-setup.py", line 144, in <module>
    args.func(**args_dict)
  File "/usr/local/lib/python3.6/dist-packages/mag_annotator/database_processing.py", line 512, in prepare_databases
    set_database_paths(**output_dbs, use_current_locs=False, update_description_db=True, start_time=start_time)
  File "/usr/local/lib/python3.6/dist-packages/mag_annotator/database_processing.py", line 360, in set_database_paths
    with open(config_loc, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/mag_annotator/CONFIG'

**Comment by shafferm** [comment]
Hello Itai,

I have never installed DRAM locally so I'm not totally sure. When you install python packages do you normally have to use sudo? DRAM writes it's configuration file into the location DRAM is installed (so in your case `/usr/local/lib/python3.6/dist-packages/mag_annotator/`). If you need to sudo to edit files in this location then yes you will need to run DRAM-setup.py with sudo but annotation and distillation will not need sudo.

Mike

PS Kelly says Hi!

**Comment by CK7** [comment]
Running DRAM-setup.py with sudo did the trick.
Could you tell me what is the description database? I may have missed that while going through the manual. It seems to have a command of its own so I assume it is not a standard database?
I've been waiting all along for Kelly's group to come up with a tool like DRAM! Please send her my warmest regards :)

**Comment by shafferm** [comment]
The description database is a sqlite database containing the descriptions of all database identifiers from all databases. It exists to speed up making the annotations file with all the annotations from all the databases. It is built from the files that are created when making all the other databases. It has its own command so that if you update a single database then you need to update the description database from all installed databases.
