### ISSUE TITLE
DRAM_setup failed for kofam db

### ISSUE THREAD

**Issue by slambrechts** [shafferm/DRAM#120]
Hi,

`DRAM-setup.py` ran successfully, except for kofam. The connection/download of the kofam profiles db failed. I am now downloading the DB manually, but I was wondering how I should run DRAM-setup.py after the download has finished, and thus how to only prepare said kofam DB and finish DRAM-setup.py?

**Comment by rmFlynn** [comment]
Hello, 
Unfortunately it is not yet possible to run partly run DRAM-setup.py, so sadly you will need to run the full setup again using the --kofam_hmm_loc to specify the profile hmm file,  and --kofam_ko_list_loc to specify the list file. Sorry for the inconvenience.

**Comment by slambrechts** [comment]
Hi,

Ok. And since all the other databases have already been downloaded by DRAM-setup.py in that same folder, should I specify all of them using `--pfam_loc`, `--dbcan_loc`, `--vogdb_loc`, etc?

**Comment by rmFlynn** [comment]
You don't have to, but you probably want to. I believe that dram will redownload these files, so if you specify them you save time uncomputation. Also it would be safer if things are failing to download.

**Comment by slambrechts** [comment]
Ok I think it worked. It says:

`0:29:41.729243: Database preparation completed
`

One other thing to mention that might help other people in a similar situation, is that the download of the kofam db failed because access to FTP servers is blocked on our HPC infrastructure (because of security reasons). The administrators advised me to check whether there are ways to use a different protocol, like SFTP or HTTPS, and download the database manually. However, when downloading the kofam db files manually from [kofam](https://www.genome.jp/ftp/db/kofam/), the ko list is named `ko_list.gz`, but `DRAM-setup.py` does not recognize that, you have to rename `ko_list.gz` to `kofam_ko_list.tsv.gz`, before you run `DRAM-setup.py prepare_databases` with `--kofam_hmm_loc` and `--kofam_ko_list_loc`.
