### ISSUE TITLE
Peptidase: No descriptions were found for your id's

### ISSUE THREAD

**Issue by npavlovikj** [shafferm/DRAM#19]
Hi,

Running `DRAM.py annotate -i SRR1238788_contigs.fa -o out --threads 16` gives me the error message:
```
/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/database_handler.py:42: UserWarning: No descriptions were found for your id's. Does this MER0255000 look like an id from peptidase_description
  warn("No descriptions were found for your id's. Does this %s look like an id from %s" % (list(ids)[0],
1 fastas found
2020-07-21 20:36:27.410332: Annotation started
0:00:00.130634: Retrieved database locations and descriptions
0:00:00.130771: Annotating SRR1238788_contigs
0:01:27.607081: Turning genes from prodigal to mmseqs2 db
0:01:38.766860: Getting hits from kofam
0:33:47.383242: Getting forward best hits from peptidase
0:35:45.081843: Getting reverse best hits from peptidase
0:36:10.493920: Getting descriptions of hits from peptidase
Traceback (most recent call last):
  File "/work/conda/envs/dram/bin/DRAM.py", line 117, in <module>
    args.func(**args_dict)
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 954, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, bit_score_threshold, rbh_bit_score_threshold, custom_db_name,
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 976, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, bit_score_threshold,
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 912, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 814, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 750, in annotate_orfs
    annotation_list.append(do_blast_style_search(query_db, db_locs['peptidase'], tmp_dir,
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 651, in do_blast_style_search
    hits = get_description(hits, header_dict)
  File "/work/conda/envs/dram/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 175, in get_peptidase_description
    header = header_dict[peptidase_hit]
KeyError: 'MER0255000'
```

I did download the peptidases dbs using `DRAM-setup.py prepare_databases`. Just to verify that the step was not corrupted as mentioned in some of the other issues here, I downloaded and indexed the db separately following the steps in https://github.com/shafferm/DRAM/blob/8596e0df405aff389419c0b3b9491c757cda1aa1/mag_annotator/database_processing.py#L222. Also, the version of `mmseqs2 ` I have in my environment is `11.e1a1c`.
If I search for "MER0255000" in the "peptidases" files, I do find a hit:
```
$ grep -rnw "MER0255000" /work/deogun/npavlovikj/conda/envs/dram/peptidases.20200708.mmsdb*
Binary file /work//conda/envs/dram/peptidases.20200708.mmsdb_h matches
Binary file /work/conda/envs/dram/peptidases.20200708.mmsdb.idx matches
/work/conda/envs/dram/peptidases.20200708.mmsdb.lookup:885370:885369	MER0255000	0
```

Can you please give me some directions on how I can fix this error?
If you need any additional information, please let me know.

P.S. I did create a conda recipe for DRAM, https://github.com/bioconda/bioconda-recipes/tree/master/recipes/dram, using the PyPI distribution and the dependences listed in the documentation here. The run dependencies can be seen here, https://github.com/bioconda/bioconda-recipes/blob/master/recipes/dram/meta.yaml, and I installed DRAM via conda in my testing environment.

Thank you,
Best Regards,
Natasha

**Comment by shafferm** [comment]
Thanks for making a bioconda recipe Natasha!

Can you send me what prints when you run `DRAM-setup.py print_config`? It does seem like something is wrong with your description database. I think if you ran `DRAM-setup.py update_description_db` and then reran your annotate command this would likely be fixed.

If you downloaded and indexed the DB on your own and didn't update the description database then that might explain it. During `prepare_databases` first the database is downloaded and processed (with the steps you followed) and then at the end of `preare_databases` the description database is built. This stores all the header information from the processed FASTAs as well as any description info for the HMMs in an sqlite database. This makes it quick to grab full database entry descriptions for significant hits during annotation. To update the description database at any time you can run `DRAM-setup.py update_description_db`. There is also a flag in the `DRAM-setup.py set_database_locations` command to update the descritiption database in case the new database files do not correspond with the entries in the description database.

**Comment by npavlovikj** [comment]
Hi @shafferm ,

Thank you so much for your prompt reply!

Based on your suggestion, I re-ran `DRAM-setup.py set_database_locations --update_description_db`, and I believe `DRAM.py annotate` is working correctly now. On our University cluster running  `DRAM-setup.py set_database_locations --update_description_db` with 10 threads took ~60 hours and ~250GB of RAM.

I have an additional question if that is ok.
If I want to use the same databases (same location) but in a different environment with `DRAM`, can I just copy the `CONFIG` file from one environment to another, or I need to re-run `DRAM-setup.py set_database_locations --update_description_db`? I guess I would like to know what files are modified with `DRAM-setup.py set_database_locations --update_description_db`, and whether I can just copy the modified files without re-running `DRAM-setup.py` in the new environment.

Thank you,
Natasha

**Comment by npavlovikj** [comment]
To answer my question for future reference  - the answer is Yes :)
Thank you for all the help, and please feel free to close this issue now.

Thank you,
Natasha

**Comment by shafferm** [comment]
Yes you can always copy around your CONFIG file. I keep one that I copy into new environments all the time.

Also in `DRAM-setup.py` there are methods to export and import CONFIG files. `DRAM-setup.py export_config` allows you to save your config to a file location of your choice. `DRAM-setup.py import_config` then lets you import a config file into a new or existing installation.

**Comment by npavlovikj** [comment]
Thank you Michael, that is good to know!
