### ISSUE TITLE
[Errors in DRAM annotate] AttributeError: 'DataFrame' object has no attribute 'get_annotations' and KeyError: 'classification'

### ISSUE THREAD

**Issue by mutantjoo0** [shafferm/DRAM#20]
Hi Mike(@shafferm ),

I realized that I kept posting on [my previous post (#9 ) about `DRAM-setup` and I think it is better make a new post here about `DRAM annotate` issue.
As you mentioned 
> [Looks like everything worked on your test set. Distillation is very fast compared to annotation! Makes it easy for subsetting your data or grouping annotations by different categories for redistilling in the future.](https://github.com/shafferm/DRAM/issues/9#issuecomment-662739875)
I redid running DRAM annotate after subsetting data by group. I used two different nodes to run DRAM annotate two sets and got two different errors as follows:

1) **110 diver MAGs** (salloc) ->error ` AttributeError: 'DataFrame' object has no attribute 'get_annotations' ` occurred after 22 hrs <- same error as [previously described](https://github.com/shafferm/DRAM/issues/9#issuecomment-663281101).
```
(DRAM) -bash-4.2$ salloc -N 1 -c 1 -n 2 --time=100:00:00 --mem=600G
salloc: Pending job allocation 66486740
salloc: job 66486740 queued and waiting for resources
salloc: Granted job allocation 66486740
salloc: Waiting for resource configuration
salloc: Nodes qml-000 are ready for job

(DRAM) bash-4.2$ DRAM.py annotate -i 'diver_MAGs/*fa' -o annotations_diver_MAGs --gtdb_taxonomy diver_bin_taxonomy.tsv --threads 40 --skip_trnascan
110 fastas found
2020-07-24 03:39:05.114663: Annotation started
0:00:00.016062: Retrieved database locations and descriptions
0:00:00.016145: Annotating GR30_maxbin2_bin.8_sub
0:00:02.972119: Turning genes from prodigal to mmseqs2 db
0:00:05.947966: Getting hits from kofam
0:07:27.442299: Getting forward best hits from peptidase
0:07:41.904579: Getting reverse best hits from peptidase
0:07:45.455031: Getting descriptions of hits from peptidase
0:07:47.152603: Getting hits from pfam
0:09:13.805968: Getting hits from dbCAN
0:09:19.306525: Getting hits from VOGDB
0:12:14.193315: Merging ORF annotations
/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py:573: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
.
.
21:53:11.749067: Annotating GR25_metabat2_bin.1
21:53:48.727226: Turning genes from prodigal to mmseqs2 db
21:53:52.241435: Getting hits from kofam
22:09:00.037555: Getting forward best hits from peptidase
22:09:35.256973: Getting reverse best hits from peptidase
22:09:44.261478: Getting descriptions of hits from peptidase
22:09:45.794218: Getting hits from pfam
22:10:09.085326: Getting hits from dbCAN
22:10:23.545279: Getting hits from VOGDB
22:16:53.180445: Merging ORF annotations
22:17:05.296726: Annotations complete, processing annotations
Traceback (most recent call last):
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/bin/DRAM.py", line 117, in <module>
    args.func(**args_dict)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 954, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, bit_score_threshold, rbh_bit_score_threshold, custom_db_name,
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 976, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, bit_score_threshold,
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 918, in annotate_fastas
    all_annotations = pd.concat([i.get_annotations() for i in annotations_list], sort=False)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 918, in <listcomp>
    all_annotations = pd.concat([i.get_annotations() for i in annotations_list], sort=False)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'get_annotations'
```
`./working_dir/` was found in output directory and 111 directories including 1 `./custom_db` and 110 MAGs were found in `./working_dir/`.
```
(DRAM) bash-4.2$ ls -hl annotations_diver_MAGs/
total 8.0K
drwxr-s--- 113 leejooy5 Reguera_Kashefi_Lab 8.0K Jul 25 01:32 working_dir
(DRAM) bash-4.2$ ls -1 annotations_diver_MAGs/working_dir/ | wc -l
111 
```
I checked outputs in each MAG directory. 
```
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/annotations.tsv | wc -l
108
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/*.faa | wc -l
108
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/*.fna | wc -l
108
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/*.gbk | wc -l
108
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/*.gff | wc -l
108
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/rrnas* | wc -l
43
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/*gbk | wc -l
108
(DRAM) bash-4.2$ ls annotations_diver_MAGs/working_dir/GR*/tmp
GR25_metabat2_bin.8_sub/tmp:
filtered_fasta.fa

GR29_metabat2_bin.4_sub/tmp:
filtered_fasta.fa
```
Among 110 inputs, 65 input MAGs showed `/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py:573: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
  warnings.warn('No rRNAs were detected, no rrnas.tsv file will be created.')` during process do not include `rnas.tsv` files and 2 inputs were filtered (<min length). My best guess is something went wrong while compiling outputs (`annotations.tsv  genes.annotated.faa  genes.annotated.fna  genes.annotated.gff  bin.gbk  rrnas.tsv  scaffolds.annotated.fa`) from each MAG into single files respectively (eg, **110** annotations.tsv in each MAG were supposed to be compiled into **1** annotations.tsv in the output directory at the end of DRAM annotate, correct?). I wonder if this can be caused by different numbers of outputs in each MAG's output directory during process (**43 of 110** inputs resulted rrnas.tsv and **2 of 110** inputs resulted empty `filtered_fasta.fa` in `/tmp` .
 

2) **146 ndiver MAGs** (dev-intel18.i) -> error `KeyError: 'classification'` occurred 
```
(DRAM) -bash-4.2$ DRAM.py annotate -i 'ndiver_MAGs/*fa' -o annotations_ndiver_MAGs --gtdb_taxonomy ndiver_bin_taxonomy.tsv --threads 36 --skip_trnascan
146 fastas found
2020-07-24 03:41:39.330298: Annotation started
0:00:00.059513: Retrieved database locations and descriptions
0:00:00.059561: Annotating GR41_1_maxbin2_bin.2
0:00:06.059163: Turning genes from prodigal to mmseqs2 db
0:00:08.342067: Getting hits from kofam
0:06:20.267469: Getting forward best hits from peptidase
0:06:27.348880: Getting reverse best hits from peptidase
0:06:30.629256: Getting descriptions of hits from peptidase
0:06:31.692387: Getting hits from pfam
0:06:55.535653: Getting hits from dbCAN
0:07:01.179826: Getting hits from VOGDB
0:09:44.279245: Merging ORF annotations
.
.
.
23:01:09.995979: Annotating GR38_metabat2_bin.1
23:01:11.833232: Turning genes from prodigal to mmseqs2 db
23:01:13.772124: Getting hits from kofam
23:07:21.135113: Getting forward best hits from peptidase
23:07:23.926104: Getting reverse best hits from peptidase
23:07:26.326673: Getting descriptions of hits from peptidase
23:07:26.476885: Getting hits from pfam
23:07:38.245764: Getting hits from dbCAN
23:07:42.538901: Getting hits from VOGDB
23:09:59.085599: Merging ORF annotations
/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py:573: UserWarning: No rRNAs were detected, no rrnas.tsv file will be created.
  warnings.warn('No rRNAs were detected, no rrnas.tsv file will be created.')
23:10:01.387239: Annotations complete, processing annotations
Traceback (most recent call last):
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'classification'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/bin/DRAM.py", line 117, in <module>
    args.func(**args_dict)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 954, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, bit_score_threshold, rbh_bit_score_threshold, custom_db_name,
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 982, in annotate_bins
    all_annotations['bin_taxonomy'] = [gtdb_taxonomy.loc[i, 'classification'] for i in all_annotations.fasta]
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 982, in <listcomp>
    all_annotations['bin_taxonomy'] = [gtdb_taxonomy.loc[i, 'classification'] for i in all_annotations.fasta]
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexing.py", line 1762, in __getitem__
    return self._getitem_tuple(key)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexing.py", line 1272, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexing.py", line 1421, in _getitem_lowerdim
    return getattr(section, self.name)[new_key]
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexing.py", line 1965, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexing.py", line 621, in _get_label
    return self.obj._xs(label, axis=axis)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/generic.py", line 3537, in xs
    loc = self.index.get_loc(key)
  File "/mnt/home/leejooy5/miniconda3/envs/DRAM/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'classification'
```
And I found output files except `annotations.tsv`  in output directory, although 146 *gbk files were found in `./genbank`.
```
(DRAM) -bash-4.2$ ls -ahl
total 406M
drwxr-s--- 3 leejooy5 Reguera_Kashefi_Lab 8.0K Jul 25 02:52 .
drwxr-s--- 8 leejooy5 Reguera_Kashefi_Lab 8.0K Jul 25 12:56 ..
drwxr-s--- 2 leejooy5 Reguera_Kashefi_Lab  16K Jul 25 02:52 genbank
-rw-r----- 1 leejooy5 Reguera_Kashefi_Lab  59M Jul 25 02:51 genes.faa
-rw-r----- 1 leejooy5 Reguera_Kashefi_Lab 148M Jul 25 02:51 genes.fna
-rw-r----- 1 leejooy5 Reguera_Kashefi_Lab  44M Jul 25 02:51 genes.gff
-rw-r----- 1 leejooy5 Reguera_Kashefi_Lab  23K Jul 25 02:51 rrnas.tsv
-rw-r----- 1 leejooy5 Reguera_Kashefi_Lab 156M Jul 25 02:51 scaffolds.fna
(DRAM) -bash-4.2$ ls genbank/ | wc -l
146
```
Collectively, both runs quitted after `Annotations complete, processing annotations`, one last process before `Completed annotations`, although errors from two runs were different each other, and error messages included descriptions about **pandas**. I checked if this can be fixed with update pandas, but it is already up to date. Also, I wonder whether using higher or smaller `--min_contig_size` may help to solve these Can you find what is wrong in my commands or data and help me? Thank you for your support.

Cheers,
Joo-Young

**Comment by shafferm** [comment]
Hey Joo-Young,

Thanks for starting a new issue.

# 1. 
You are right that this is because of bins with no contigs that meet the minimum contig length threshold. This is an artifact of an older version of DRAM and I had not hit this issue before. To fix it right now you can run with a lower minimum contig size but then you have to reannotate. If you are find with only having the bins where at least one contig met minimum contig size then you can merge the annotation files from the working directory yourself. This is easy to do in python with pandas and I could give you a quick list of commands do to that if you are comfortable. I will fix this in the next release of DRAM.

#2.
I think this issue is because of the format of your gtdb or other taxonomy file. Is this the file called `gtdbtk.bac120.summary.tsv` or `gtdbtk.ar122.summary.tsv` if you used GTDB. Otherwise it needs to be a tab delimited files with the first column having your bin names and another column with the header 'classification'.

**Comment by mutantjoo0** [comment]
Hi Mike,

Thanks to your valuable supports, I was able to complete my first DRAM running. Distilled Liquors are so beautiful!
![image](https://user-images.githubusercontent.com/37589973/90278809-08797800-de36-11ea-8073-c8e3625e0926.png)

Stay safe and healthy

**Comment by Sewunet-Abera** [comment]
Michael and Lee,
I run into this issue as I was looking for a help on DRAM.
I'm a newbie to DRAM, but I'm also excited such a tool existed that I can get all the annotation from different db's at once.
Followed the instructions and manged to get my annotations.tsv file (half a million rows of file).
Then I tried to import that into R to count my genes per sample but in some annotations a single column has multiple ";" separated gene names or functions or their description.
And R didn't like that and I'm stack at that point right now.
I was wondering if you could help me out on how to proceed with the annotations.tsv for downstream statistical analysis pls?

Greetings
Sewunet A.

**Comment by abarka90** [comment]
Hi @shafferm,
Regarding the comment you gave here:

"You are right that this is because of bins with no contigs that meet the minimum contig length threshold. This is an artifact of an older version of DRAM and I had not hit this issue before. To fix it right now you can run with a lower minimum contig size but then you have to reannotate. If you are fine with only having the bins where at least one contig met minimum contig size then you can merge the annotation files from the working directory yourself. **This is easy to do in python with pandas and I could give you a quick list of commands do to that if you are comfortable.** I will fix this in the next release of DRAM."

I got the same issue. Could you please write here the list of commands to merge the annotation files from the working directory?

Thank you,
Amit

**Comment by rmFlynn** [comment]
The  command is `DRAM.py merge_annotations -i ./folder_with_dram_output_folders_all_together/* -o combined_anotations` but this should be fixed, what version of dram are you useing?
