### ISSUE TITLE
List of genes that go into the five major categories of metabolism

### ISSUE THREAD

**Issue by gtrubl** [shafferm/DRAM#24]
Hi Mike,

Thanks for all your previous help. I am going through my non-VirSorted viruses that were annotated with DRAMv and I would like to manually distill my results. Is there a list that you used with your script to label what gene goes into which of five major categories (energy, transporters, miscellaneous, carbon utilization, and organic nitrogen)? I thought maybe this would be in the supplementary files of the paper, but I only see the info for the example data (e.g., Supplementary File 5).

Do you have a complete list someone of genes and their category?

Update. I think I found it in the DRAM data in file "genome_summary_form". Is this it and complete?

Thanks,

Gary

**Comment by shafferm** [comment]
That's right Gary. It's the genome_summary_form that we use to build the distillate file `metabolism_summary.xlsx` for DRAM. You can run your `annotations.tsv` file that came out of `DRAM-v.py annotate` and run it through `DRAM.py distill` and you will get the `metabolism_summary.xlsx` result automatically.
