### ISSUE TITLE
prepare_databases not completing

### ISSUE THREAD

**Issue by btemperton** [shafferm/DRAM#26]
I installed DRAM on our HPC without issue using the attached `conda` environment and then set about running the `prepare_databases` script as follows:

```
conda activate DRAM
DRAM-setup.py prepare_databases --output_dir DRAM_data \
--threads 32 \
--kofam_hmm_loc DRAM_data/kofam_profiles.tar.gz \
--uniref_loc DRAM_data/uniref90.fasta.gz \
--pfam_loc DRAM_data/Pfam-A.full.gz \
--pfam_hmm_dat DRAM_data/Pfam-A.hmm.dat.gz \
--dbcan_loc DRAM_data/dbCAN-HMMdb-V8.txt \
--dbcan_fam_activities DRAM_data/CAZyDB.07312019.fam-activities.txt \
--vogdb_loc DRAM_data/vog.hmm.tar.gz \
--vog_annotations DRAM_data/vog_annotations_latest.tsv.gz \
--viral_loc DRAM_data/viral.merged.protein.faa.gz \
--peptidase_loc DRAM_data/pepunit.lib \
2>&1 | tee DRAM.install.3.log
```

I initially tried this without specifying file locations and it downloaded the files and processed them, but still didn't complete. I then tried it with the above commands using the downloaded files. In both cases, it appears to have  completed all the downloads and creation of the MMseq databases (file structure attached). However, the script is still running after 48 hours and hasn't touched the file system for the last 12 at least. There are no error messages and the machine it is running on has 3Tb of RAM.

Curiously, there is absolutely no output to the log file, so I'm not sure where the print statements in the script are printing to!
 
I would be grateful if you could look at the file structure and let me know at what stage you think it has failed, and why it hasn't thrown any error.
[Archive.zip](https://github.com/shafferm/DRAM/files/5150875/Archive.zip)

**Comment by shafferm** [comment]
Interesting and the file structure outline is super helpful!  It seems to me like something is going wrong either with processing the header files to generate the description database or writing to the description database. It seems like all the data is there but the description database is not it's full size (on our system the fully populated `description_db.sqlite` file is 19 GB). I wish the log was writing because then I could see if it is something to do with the size of uniref90 causing problems.

My idea on how to get around the problem is to kill the current process. Then since the databases have all processed we can use those and then rebuild the description database. The command to do that is this:

```bash
conda activate DRAM
DRAM-setup.py set_database_locations \
    --kofam_hmm_loc DRAM_data/kofam_profiles.hmm \
    --kofam_ko_list_loc DRAM_data/kofam_ko_list.tsv \
    --uniref_db_loc DRAM_data/uniref90.20200829.mmsdb \
    --pfam_db_loc DRAM_data/pfam.mmspro \
    --pfam_hmm_dat DRAM_data/Pfam-A.hmm.dat.gz \
    --dbcan_db_loc DRAM_data/dbCAN-HMMdb-V8.txt \
    --dbcan_fam_activities DRAM_data/CAZyDB.07312019.fam-activities.txt \
    --vogdb_db_loc DRAM_data/vog_latest_hmms.txt \
    --vog_annotations DRAM_data/vog_annotations_latest.tsv.gz \
    --viral_db_loc DRAM_data/refseq_viral.20200829.mmsdb \
    --peptidase_db_loc DRAM_data/peptidases.20200829.mmsdb \
    --description_db_loc DRAM_data/description_db.sqlite \
    --genome_summary_form_loc DRAM_data/genome_summary_form.20200829.tsv \
    --module_step_form_loc DRAM_data/module_step_form.20200829.tsv \
    --etc_module_database_loc DRAM_data/etc_mdoule_database.20200829.tsv \
    --function_heatmap_form_loc DRAM_data/function_heatmap_form.20200829.tsv \
    --amg_database_loc DRAM_data/amg_database.20200829.tsv \
    --update_description_db
```

**Comment by btemperton** [comment]
That worked! At least I think it did - it's now throwing a KeyError when I include either the `checkm` or `gtdbtk` output files. What format are these supposed to be in? Do we need to strip out the headers etc? Could you post a working example of each?

**Comment by shafferm** [comment]
Great! If it is getting to throwing you an error when adding taxonomy and quality then it sounds like it's getting just about to the end.

For `checkm` and `gtdbtk` you do need to keep headers.

For `checkm` the file you need is the tab delimited qa file. This can be generated with the `qa` command or by when using `lineage_wf` using the `--table_table` and `-f` flags. DRAM assumes the first column is the bin names and then looks for the `Completeness` and `Contamination` columns. You don't need to use `checkm` or the ` checkm` results file directly. All you really need is a table delimited file with the first column being bin names and two other columns called `Completeness` and `Contamination`.

For `gtdbtk` the files you want are `gtdbtk.ar122.summary.tsv` and `gtdbtk.bac120.summary.tsv`. You can concatenate these two files and then use the results from both or only use one if all your bins are bacteria or archaea. Similar to the `checkm` file the only columns used are the first column for bins and a column called `classification` so you could use a different file as long as it has those columns.

I'll work on getting examples into the wiki so this is more clear!

**Comment by btemperton** [comment]
I basically gave up trying to get this to finish on our HPC as it kept getting stuck and timing out . In the end, I launched a virtual machine with ubuntu 18, built the databases on there (including uniref90 - took about 20 hours), and copied them back over to the HPC. I then reinstalled DRAM on the HPC and ran the `DRAM-setup.py set_database_locations` script pointing at the files I'd copied across.

I can now run DRAM on the HPC without issue, using the `uniref90` database on our high memory nodes.

**Comment by shafferm** [comment]
@mw55309 I think that is a great idea that I had not considered. I will try to figure out how to integrate snakemake into DRAM in DRAM 2.

It seems like processing with mmseqs2 and HMMER takes around the same amount of time regardless of system but on some systems building the `description_db.sqlite` takes 10+ hours. On the two systems I have personally set up DRAM it only takes about 2. Is anyone here a SQL wiz who has ideas on why that could be happening? Is it all about disk write speed?

**Comment by nejcstopno** [comment]
@shafferm regarding building the `description_db.sqlite`, what is the size of it? I am at this step for over 15h and the size at the moment is 12G. I have roughly 30h left before the job runs out of time (using 1.4T memory) but can request an extension for this job. Knowing how large the final `description_db.sqlite` is would help me to estimate how much more time I need to request. Thanks

**Comment by mw55309** [comment]
Yes, building the sqlite DB is taking an absolute age.

Mine is currently at 4.6Gb with after 48 hours of building the DB....

**Comment by mw55309** [comment]
@btemperton how big a VM did you use and on what cloud provider?

Currently just populating the sqlite DB is going to take my process 19 days.

It builds all the DBs fine, the major bottleneck is the sqlite database

**Comment by mw55309** [comment]
Hi, just to wind this up, I found a new server with faster disk and my job completed in 8 hours. Previously it was set to take 19 days! This is simply a disk/network write issue and writing millions of rows of UniProt data into the SQLite database simply takes a *very long time* when you're not on super-fast disk.

I started this which might help others in the same situation: https://github.com/mw55309/DRAM_hacks

**Comment by shafferm** [comment]
Thanks for digging into this @mw55309. You were able to figure out what I've been banging my head against the wall trying to figure out for months. The two servers I work on are pretty much the same configuration so I wasn't able to replicate the long database build times. You've also found my biggest software engineering blind spot in databases. If you or anyone else has a suggestion for breaking up the actual database building phase or if I could change to another file based or otherwise very portable database I'd by happy to chat.

One other thing. In `DRAM-setup.py` there is a command `update_description_db` so if the CONFIG file is fully set up with all database paths then there is enough information to build all the databases and you can just run `DRAM-setup.py update_description_db` to build the description database.

**Comment by Xuyang-Feng** [comment]
> That worked! At least I think it did - it's now throwing a KeyError when I include either the `checkm` or `gtdbtk` output files. What format are these supposed to be in? Do we need to strip out the headers etc? Could you post a working example of each?

Hi, I try the same method that @shafferm said. And it also worked well. However, I am wondered that how big is the description_db size. My description_db is only 330M. I don't know whether it is the right size, as I saw others' db size is almost more than 10 Gb. Here is my database_set_up log.
'2024-11-14 12:02:15,660 - Logging to console
2024-11-14 12:02:16,388 - Description updated for the uniref database
2024-11-14 12:02:34,845 - Description updated for the viral database
2024-11-14 12:06:52,133 - Description updated for the peptidase database
2024-11-14 12:06:52,930 - Description updated for the pfam database
2024-11-14 12:06:53,165 - Description updated for the dbcan database
2024-11-14 12:06:55,256 - Description updated for the vogdb database
'

**Comment by Sneakypeat** [comment]
They need to hire some good programmers. Its extremely frustrating.
