### ISSUE TITLE
What is the source of the KOfam database?

### ISSUE THREAD

**Issue by mw55309** [shafferm/DRAM#29]
Or do you use the web version?

**Comment by shafferm** [comment]
The profiles are downloaded from here: ftp://ftp.genome.jp/pub/db/kofam/profiles.tar.gz
And the profile names/metadata and cutoffs are downloaded from: ftp://ftp.genome.jp/pub/db/kofam/ko_list.gz

The links to the FTP site are in the Download section here: https://www.genome.jp/tools/kofamkoala/
