### ISSUE TITLE
 CalledProcessError(retcode, process.args,

### ISSUE THREAD

**Issue by LuDeChen** [shafferm/DRAM#31]
Very nice pipeline.when I use it, I meet an error, can youu help me,Thanks very much.

--------
 File "/bioinf/home/dlu/miniconda3/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hmmsearch', '--domtblout', 'genome-fasta-2-refine_change_DRAM/working_dir/3-1138/tmp/kofam_profile.b6', '--cpu', '60', '/scratch/dlu/DRAM_data/kofam_profiles.hmm', 'genome-fasta-2-refine_change_DRAM/working_dir/3-1138/tmp/genes.faa']' died with <Signals.SIGSEGV: 11>.

**Comment by shafferm** [comment]
Hi,

Can you send me the results of what happens when you rung `DRAM-setup.py version` and `DRAM-setup.py print_config`?

You can also attempt to run that command outside of DRAM and you should get a more informative error message. That command would be `hmmsearch --domtblout genome-fasta-2-refine_change_DRAM/working_dir/3-1138/tmp/kofam_profile.b6 --cpu', '60 /scratch/dlu/DRAM_data/kofam_profiles.hmm genome-fasta-2-refine_change_DRAM/working_dir/3-1138/tmp/genes.faa`.

**Comment by GaryZhangYue** [comment]
Hi,

I had a similar issue during setting up DRAM. Could you please a look for me? Thank you so much!

No error info was generated by conda env create -f environment.yaml -n DRAM.

Then I got an error HERE:
DRAM-setup.py prepare_databases --output_dir /home-4/yzhan231@jhu.edu/work/yuezhang/lib/DRAM
2021-07-01 14:48:30.314255: Database preparation started
Traceback (most recent call last):
  File "/home-4/yzhan231@jhu.edu/.conda/envs/DRAM/bin/DRAM-setup.py", line 146, in <module>
    args.func(**args_dict)
  File "/home-4/yzhan231@jhu.edu/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 457, in prepare_databases
    output_dbs['uniref_db_loc'] = download_and_process_uniref(uniref_loc, temporary, uniref_version=uniref_version,
  File "/home-4/yzhan231@jhu.edu/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/database_processing.py", line 112, in download_and_process_uniref
    make_mmseqs_db(uniref_fasta_zipped, uniref_mmseqs_db, create_index=True, threads=threads, verbose=verbose)
  File "/home-4/yzhan231@jhu.edu/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 46, in make_mmseqs_db
    run_process(['mmseqs', 'createdb', fasta_loc, output_loc], verbose=verbose)
  File "/home-4/yzhan231@jhu.edu/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home-4/yzhan231@jhu.edu/.conda/envs/DRAM/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createdb', '/home-4/yzhan231@jhu.edu/work/yuezhang/lib/DRAM/database_files/uniref90.fasta.gz', '/home-4/yzhan231@jhu.edu/work/yuezhang/lib/DRAM/database_files/uniref90.20210701.mmsdb']' died with <Signals.SIGKILL: 9>.

Here is the output for DRAM-setup.py version and print_config
(DRAM) [yzhan231@jhu.edu@compute0782 DRAM]$ DRAM-setup.py version
1.2.2
(DRAM) [yzhan231@jhu.edu@compute0782 DRAM]$ DRAM-setup.py print_config
KEGG db: None
KOfam db: None
KOfam KO list: None
UniRef db: None
Pfam db: None
Pfam hmm dat: None
dbCAN db: None
dbCAN family activities: None
RefSeq Viral db: None
MEROPS peptidase db: None
VOGDB db: None
VOG annotations: None
Description db: None
Genome summary form: /Users/shafferm/lab/DRAM/data/genome_summary_form.tsv
Module step form: /Users/shafferm/lab/DRAM/data/module_step_form.tsv
ETC module database: /Users/shafferm/lab/DRAM/data/etc_module_database.tsv
Function heatmap form: /Users/shafferm/lab/DRAM/data/function_heatmap_form.tsv
AMG database: /Users/shafferm/lab/DRAM/data/amg_database.tsv

Here is what has been downloaded to database dir
(DRAM) [yzhan231@jhu.edu@compute0782 DRAM]$ ls database_files/
uniref90.20210701.mmsdb.0    uniref90.20210701.mmsdb_h.1        uniref90.20210701.mmsdb_h.index.10  uniref90.20210701.mmsdb.index.11
uniref90.20210701.mmsdb.1    uniref90.20210701.mmsdb_h.10       uniref90.20210701.mmsdb_h.index.11  uniref90.20210701.mmsdb.index.12
uniref90.20210701.mmsdb.10   uniref90.20210701.mmsdb_h.11       uniref90.20210701.mmsdb_h.index.12  uniref90.20210701.mmsdb.index.13
uniref90.20210701.mmsdb.11   uniref90.20210701.mmsdb_h.12       uniref90.20210701.mmsdb_h.index.13  uniref90.20210701.mmsdb.index.14
uniref90.20210701.mmsdb.12   uniref90.20210701.mmsdb_h.13       uniref90.20210701.mmsdb_h.index.14  uniref90.20210701.mmsdb.index.15
uniref90.20210701.mmsdb.13   uniref90.20210701.mmsdb_h.14       uniref90.20210701.mmsdb_h.index.15  uniref90.20210701.mmsdb.index.16
uniref90.20210701.mmsdb.14   uniref90.20210701.mmsdb_h.15       uniref90.20210701.mmsdb_h.index.16  uniref90.20210701.mmsdb.index.17
uniref90.20210701.mmsdb.15   uniref90.20210701.mmsdb_h.16       uniref90.20210701.mmsdb_h.index.17  uniref90.20210701.mmsdb.index.18
uniref90.20210701.mmsdb.16   uniref90.20210701.mmsdb_h.17       uniref90.20210701.mmsdb_h.index.18  uniref90.20210701.mmsdb.index.19
uniref90.20210701.mmsdb.17   uniref90.20210701.mmsdb_h.18       uniref90.20210701.mmsdb_h.index.19  uniref90.20210701.mmsdb.index.2
uniref90.20210701.mmsdb.18   uniref90.20210701.mmsdb_h.19       uniref90.20210701.mmsdb_h.index.2   uniref90.20210701.mmsdb.index.20
uniref90.20210701.mmsdb.19   uniref90.20210701.mmsdb_h.2        uniref90.20210701.mmsdb_h.index.20  uniref90.20210701.mmsdb.index.21
uniref90.20210701.mmsdb.2    uniref90.20210701.mmsdb_h.20       uniref90.20210701.mmsdb_h.index.21  uniref90.20210701.mmsdb.index.22
uniref90.20210701.mmsdb.20   uniref90.20210701.mmsdb_h.21       uniref90.20210701.mmsdb_h.index.22  uniref90.20210701.mmsdb.index.23
uniref90.20210701.mmsdb.21   uniref90.20210701.mmsdb_h.22       uniref90.20210701.mmsdb_h.index.23  uniref90.20210701.mmsdb.index.24
uniref90.20210701.mmsdb.22   uniref90.20210701.mmsdb_h.23       uniref90.20210701.mmsdb_h.index.24  uniref90.20210701.mmsdb.index.25
uniref90.20210701.mmsdb.23   uniref90.20210701.mmsdb_h.24       uniref90.20210701.mmsdb_h.index.25  uniref90.20210701.mmsdb.index.26
uniref90.20210701.mmsdb.24   uniref90.20210701.mmsdb_h.25       uniref90.20210701.mmsdb_h.index.26  uniref90.20210701.mmsdb.index.27
uniref90.20210701.mmsdb.25   uniref90.20210701.mmsdb_h.26       uniref90.20210701.mmsdb_h.index.27  uniref90.20210701.mmsdb.index.28
uniref90.20210701.mmsdb.26   uniref90.20210701.mmsdb_h.27       uniref90.20210701.mmsdb_h.index.28  uniref90.20210701.mmsdb.index.29
uniref90.20210701.mmsdb.27   uniref90.20210701.mmsdb_h.28       uniref90.20210701.mmsdb_h.index.29  uniref90.20210701.mmsdb.index.3
uniref90.20210701.mmsdb.28   uniref90.20210701.mmsdb_h.29       uniref90.20210701.mmsdb_h.index.3   uniref90.20210701.mmsdb.index.30
uniref90.20210701.mmsdb.29   uniref90.20210701.mmsdb_h.3        uniref90.20210701.mmsdb_h.index.30  uniref90.20210701.mmsdb.index.31
uniref90.20210701.mmsdb.3    uniref90.20210701.mmsdb_h.30       uniref90.20210701.mmsdb_h.index.31  uniref90.20210701.mmsdb.index.4
uniref90.20210701.mmsdb.30   uniref90.20210701.mmsdb_h.31       uniref90.20210701.mmsdb_h.index.4   uniref90.20210701.mmsdb.index.5
uniref90.20210701.mmsdb.31   uniref90.20210701.mmsdb_h.4        uniref90.20210701.mmsdb_h.index.5   uniref90.20210701.mmsdb.index.6
uniref90.20210701.mmsdb.4    uniref90.20210701.mmsdb_h.5        uniref90.20210701.mmsdb_h.index.6   uniref90.20210701.mmsdb.index.7
uniref90.20210701.mmsdb.5    uniref90.20210701.mmsdb_h.6        uniref90.20210701.mmsdb_h.index.7   uniref90.20210701.mmsdb.index.8
uniref90.20210701.mmsdb.6    uniref90.20210701.mmsdb_h.7        uniref90.20210701.mmsdb_h.index.8   uniref90.20210701.mmsdb.index.9
uniref90.20210701.mmsdb.7    uniref90.20210701.mmsdb_h.8        uniref90.20210701.mmsdb_h.index.9   uniref90.20210701.mmsdb.source
uniref90.20210701.mmsdb.8    uniref90.20210701.mmsdb_h.9        uniref90.20210701.mmsdb.index.0     uniref90.fasta.gz
uniref90.20210701.mmsdb.9    uniref90.20210701.mmsdb_h.index.0  uniref90.20210701.mmsdb.index.1
uniref90.20210701.mmsdb_h.0  uniref90.20210701.mmsdb_h.index.1  uniref90.20210701.mmsdb.index.10

Thank you!
