### ISSUE TITLE
SIGSEGV error

### ISSUE THREAD

**Issue by mTangherlini** [shafferm/DRAM#34]
Hi everybody,
I'm trying to annotate a bunch of MAGs with DRAM. While it works perfectly on most of them, it raises a weird error on a single one. In particular, this is the error message:
`2020-10-05 14:26:27.861795: Annotation started
0:00:00.168350: Retrieved database locations and descriptions
0:00:00.168491: Annotating VH23renamed
0:00:29.219877: Turning genes from prodigal to mmseqs2 db
0:00:34.387347: Getting hits from kofam
Traceback (most recent call last):
  File "/opt/miniconda3/envs/DRAM/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 963, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 1000, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 919, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 820, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 731, in annotate_orfs
    annotation_list.append(run_hmmscan_kofam(gene_faa, db_locs['kofam'], tmp_dir,
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 236, in run_hmmscan_kofam
    run_process(['hmmsearch', '--domtblout', output, '--cpu', str(threads), kofam_hmm, gene_faa], verbose=verbose)
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/opt/miniconda3/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hmmsearch', '--domtblout', 'annotation_VH23/working_dir/VH23renamed/tmp/kofam_profile.b6', '--cpu', '32', '/home/mtangherlini/DRAM_data/kofam_profiles.hmm', 'annotation_VH23/working_dir/VH23renamed/tmp/genes.faa']' died with <Signals.SIGSEGV: 11>.
`
What should I do now? I tried renaming sequence headers, but it didn't seem to fix the issue - which, I repeat, only occurs with this particular MAG.

**Comment by shafferm** [comment]
That's frustrating that it is just this one bin. Can you try running that hmmsearch command directly to see if it gives you a more meaningful error message?

The command is `hmmsearch --domtblout annotation_VH23/working_dir/VH23renamed/tmp/kofam_profile.b6 --cpu 32 /home/mtangherlini/DRAM_data/kofam_profiles.hmm annotation_VH23/working_dir/VH23renamed/tmp/genes.faa`.

**Comment by mTangherlini** [comment]
Thanks for the suggestion. I tried running the command, but all I get is another segmentation fault with no better definition. What could I do?

> That's frustrating that it is just this one bin. Can you try running that hmmsearch command directly to see if it gives you a more meaningful error message?
> 
> The command is `hmmsearch --domtblout annotation_VH23/working_dir/VH23renamed/tmp/kofam_profile.b6 --cpu 32 /home/mtangherlini/DRAM_data/kofam_profiles.hmm annotation_VH23/working_dir/VH23renamed/tmp/genes.faa`.

**Comment by mTangherlini** [comment]
I also tried to concatenate all contigs to check whether it's an issue related to some bad characters or the like, yet DRAM halts with the same error.

**Comment by shafferm** [comment]
Can you send me the bin/contig that is throwing the error to see if I can reproduce it? Right now it seems to me that this is likely either a HMMER bug or a prodigal bug that isn't showing up until the HMMER search.

**Comment by mTangherlini** [comment]
> Can you send me the bin/contig that is throwing the error to see if I can reproduce it? Right now it seems to me that this is likely either a HMMER bug or a prodigal bug that isn't showing up until the HMMER search.
Of course, here it is. Thanks for the help!

[VH23.fasta.zip](https://github.com/shafferm/DRAM/files/5353029/VH23.fasta.zip)

**Comment by mTangherlini** [comment]
Hello,
Sorry to bother you, but I need to know whether you managed to check this bin and to see if still raises errors to DRAM.
Best regards

> Can you send me the bin/contig that is throwing the error to see if I can reproduce it? Right now it seems to me that this is likely either a HMMER bug or a prodigal bug that isn't showing up until the HMMER search.

**Comment by shafferm** [comment]
Good timing! I just ran it yesterday and it worked for me. I have attached the results [here](https://github.com/shafferm/DRAM/files/5459887/VH23_anno.tar.gz).

If you have installed DRAM in a conda environment could you post the results of running `conda list` inside that environment?

**Comment by mTangherlini** [comment]
Hi,
Sorry for taking so much in replying to your requests. I asked the cluster admin to carry out some checks, but he decided to re-install it manually from scratch and, well, DRAM now seems to work. So, yes, the issue might have been related to some conda package mismatch.
Thanks for taking the time to carry out the check!

**Comment by bcpd** [comment]
FWIW, I was able to solve this issue by setting hmmer=3.3.0 in the yaml file. Apparently, the default hmmer version installed by DRAM, 3.3.1 (as of Jan 13th), is the culprit: see https://github.com/takaram/kofam_scan/issues/19

**Comment by shafferm** [comment]
Thanks for finding that issue @bcpd. I added to the DRAM `environment.yaml` file to skip hmmer version 3.3.1. Upgrading HMMER should fix this issue.
