### ISSUE TITLE
Possibility to continue run?

### ISSUE THREAD

**Issue by Camaika** [shafferm/DRAM#36]
Hi,

I have two directories from DRAM.py annotate: 
-One with the final results of about 300 input files, DRAM ran all the way through and created the final merged files
-One with the working_dir of around 7000 input files. DRAM was stopped due to space issues, before it had the chance to do the final merging step.

Is there a possibility to make DRAM merge all ~7300 files into the final output files. Or is it possible to do the merging manually?

**Comment by shafferm** [comment]
Yes it is possible.

To merge the one that stopped early you can run the script here: https://gist.github.com/shafferm/99b1222f0a75dae0a0528b948d133e62

You can download that script and then run it from your output directory where the folder `working_dir` is.

Then to merge the two completed DRAM annotations you will have to merge manually. With fasta files that is easy as you can just cat them together. With the annotations files you will need to go into python and run these commands:

```python
import pandas as pd

annotations1 = pd.read_annotations("/path/to/annotations.tsv", sep='\t', index_col=0)
annotations2 = pd.read_annotations("/path/to/other/annotations.tsv", sep='\t', index_col=0)
merged_annotations = pd.concat([annotations1, annotations2])
merged_annotations.to_csv("path/to/output/annotations.tsv", sep='\t')
```

Hope that works.

**Comment by Camaika** [comment]
Thank you very much for your help, it worked like a charm!

(It should be pd.read_table though I guess, for concatenating but only keeping one header. But that worked.)
