### ISSUE TITLE
Genome stats reg

### ISSUE THREAD

**Issue by srisvs33** [shafferm/DRAM#37]
Dear Michael

Greetings.

Thank you for developing this wonderful package. I have a query related to genome stats. How the quality of genome bins are assessed?  In the datasets i used, assembly quality results says, all the MAGS were Medium except few which were high, even though it has completeness of above 95% and contamination less than 1 %. 

Also is there a software that you can recommend for visualization of MAGs. Sorry if the question is very much primitive. I am very new to MAG world!

Many thanks in advance

Kind regards
Venkat

**Comment by shafferm** [comment]
Hi Venkat,

We assess quality of MAGs based on the MiMAG standard (defined in this paper: https://www.nature.com/articles/nbt.3893). High quality genomes have all 3 rRNA genes and at least 18 tRNAs as well as having contigs which span repetitive regions. Measuring that last part is not possible with DRAM right now. So as a precaution we only grant medium quality in the genome stats file. If you manually evaluate your MAGs and find that they meet all the criteria to be high quality then you can change that value on your own.

What do characteristics of your MAGs do you want to visualize? If you want to make trees or look further in the metabolisms present in MAGs I can make some recommendations.

Mike

**Comment by srisvs33** [comment]
Dear Mike

Thanks for your prompt response.  i am especially plans look into further metabolisms, also planning to work on closely related MAGS and their phylogenomics. 

Thanks for your help

regards
Venkat
