### ISSUE TITLE
DRAM.py annotate ValueError('Database does not exist at path %s' % database_loc)

### ISSUE THREAD

**Issue by qiyanang** [shafferm/DRAM#38]
Hi Michael,

Thanks for developing this package and for providing help with troubleshooting.

I'm facing errors with the DRAM.py annotate command, which gives the following error:
ValueError: Database does not exist at path /.../description_db.sqlite.

I have double-checked using print_config command that the full paths to the databases are provided and are accurate.

Might you have any idea what could be wrong?

**Comment by shafferm** [comment]
Hi,

I can't think of anything off the top of my header. Are you running DRAM on a server? If so it might be that when a job is running it can't find the databases even though it can when you are on the head node. Can you post the results of running `DRAM.py print_config` as well as the full output from the error?

Mike

**Comment by qiyanang** [comment]
Hi Michael,

Turns out I forgot to avoid absolute paths when compressing the databases into a single file using tar. Silly mistake on my part.

The pipeline works perfectly now, thank you!
