### ISSUE TITLE
Error in annotation

### ISSUE THREAD

**Issue by nightkid03** [shafferm/DRAM#39]
Hi DRAM team,
I used DRAM.py annotate for my 2500+ genomes. Most of them succeed, but 23 failed, which is really confusing. 

**One of the genome file attached**
[1070-LCH1817.23.fa.txt](https://github.com/shafferm/DRAM/files/5469596/1070-LCH1817.23.fa.txt)

**The command is: [kofam for kegg, no uniref**]
DRAM.py annotate -i 1070-LCH1817.23.fa -o 1070-LCH1817.23.annotation --threads 16 --verbose

**The error is:**
Traceback (most recent call last):
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 963, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 1000, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 919, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 820, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 731, in annotate_orfs
    annotation_list.append(run_hmmscan_kofam(gene_faa, db_locs['kofam'], tmp_dir,
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/annotate_bins.py", line 236, in run_hmmscan_kofam
    run_process(['hmmsearch', '--domtblout', output, '--cpu', str(threads), kofam_hmm, gene_faa], verbose=verbose)
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/projects/f_lz332/software/miniconda3/envs/DRAM/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['hmmsearch', '--domtblout', '1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/kofam_profile.b6', '--cpu', '16', '/projectsp/f_lz332/software/miniconda3/envs/DRAM/Database/kofam_profiles.hmm', '1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/genes.faa']' died with <Signals.SIGSEGV: 11>.

**The pro file is:**
Sat Oct 31 12:51:58 EDT 2020
1 fastas found
2020-10-31 12:52:03.686143: Annotation started
0:00:00.044194: Retrieved database locations and descriptions
0:00:00.044254: Annotating 1070-LCH1817.23
0:00:20.570546: Turning genes from prodigal to mmseqs2 db
0:00:24.285523: Getting hits from kofam
Sat Oct 31 12:57:24 EDT 2020

**Comment by nightkid03** [comment]
Does anyone have some thoughts?

**Comment by shafferm** [comment]
Hey sorry for the slow reply. Can you try running that command where it broke directly to see if you get a better error message? The command is `hmmsearch --domtblout 1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/kofam_profile.b6 --cpu 16 /projectsp/f_lz332/software/miniconda3/envs/DRAM/Database/kofam_profiles.hmm 1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/genes.faa`. I will try it on my system and see if it works on my end.

**Comment by nightkid03** [comment]
> Hey sorry for the slow reply. Can you try running that command where it broke directly to see if you get a better error message? The command is `hmmsearch --domtblout 1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/kofam_profile.b6 --cpu 16 /projectsp/f_lz332/software/miniconda3/envs/DRAM/Database/kofam_profiles.hmm 1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/genes.faa`. I will try it on my system and see if it works on my end.

Thank you. I have tried what you said. 
The job ran for a while and had error as 
/var/lib/slurm/slurmd/job3635136/slurm_script: line 17: 119002 Segmentation fault      hmmsearch --domtblout 1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/kofam_profile.b6 --cpu 16 /projectsp/f_lz332/software/miniconda3/envs/DRAM/Database/kofam_profiles.hmm 1070-LCH1817.23.annotation/working_dir/1070-LCH1817.23/tmp/genes.faa

sacct info is 
 CPUTime     MaxRSS 
---------- ---------- 
  01:06:40            
  01:06:40    156156K 
  01:06:40      1356K

**Comment by shafferm** [comment]
Hmm, still not a very helpful error from hmmer there. Can you send me the output of `conda list` from inside your DRAM environment? I'm running your genome on my system now. It looks like this error might be related to #34.

**Comment by nightkid03** [comment]
> Hmm, still not a very helpful error from hmmer there. Can you send me the output of `conda list` from inside your DRAM environment? I'm running your genome on my system now. It looks like this error might be related to #34.

Output of "conda list" as below:
# packages in environment at /projects/f_lz332/software/miniconda3/envs/DRAM:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
altair                    4.1.0                      py_1    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
barrnap                   0.9                           3    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachecontrol              0.12.6                     py_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.3           py38h5bae8af_0    conda-forge
chardet                   3.0.4           py38h32f6830_1007    conda-forge
cryptography              3.1.1            py38h766eaa4_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py38h950e882_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dram-bio                  1.1.1                    pypi_0    pypi
entrypoints               0.3             py38h32f6830_1001    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
gawk                      5.1.0                h516909a_0    conda-forge
gdbm                      1.18                 h0a1914f_2    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
hdmedians                 0.14.1           py38hab2c0dc_0    conda-forge
hmmer                     3.3.1                he1b5a44_0    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        2.0.0            py38h32f6830_0    conda-forge
importlib_metadata        2.0.0                         0    conda-forge
infernal                  1.1.2                h516909a_3    bioconda
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
ipython                   7.18.1           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.16.0                     py_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
libgomp                   9.3.0               h24d8f2e_16    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py38h91b0d89_0    conda-forge
mmseqs2                   12.113e3             h2d02072_0    bioconda
more-itertools            8.5.0                      py_0    conda-forge
msgpack-python            1.0.0            py38hbf85e49_1    conda-forge
natsort                   7.0.1                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.1           py38hbc27379_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openmp                    7.0.0                h2d50403_0    conda-forge
openpyxl                  3.0.5                      py_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.2            py38h950e882_0    conda-forge
parallel                  20200922                      0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h9776b28_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pluggy                    0.13.1           py38h32f6830_2    conda-forge
prodigal                  2.6.3                h516909a_2    bioconda
prompt-toolkit            3.0.7                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
pytest                    6.1.0            py38h32f6830_0    conda-forge
python                    3.8.5           h1103e12_9_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ruby                      2.6.6                hebe951e_0    conda-forge
scikit-bio                0.5.6            py38h8790de6_2    conda-forge
scikit-learn              0.23.2           py38hee58b96_0    conda-forge
scipy                     1.5.2            py38h8c5af15_0    conda-forge
setuptools                49.6.0           py38h32f6830_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.19           py38h1e0a361_0    conda-forge
sqlite                    3.33.0               h4cf870e_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
traitlets                 5.0.4                      py_1    conda-forge
trnascan-se               2.0.6           pl526h516909a_0    bioconda
urllib3                   1.25.10                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.2.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by shafferm** [comment]
It worked on my system. [Here](https://github.com/shafferm/DRAM/files/5646298/anno.tar.gz) are the results if you want to merge this into your results. I am going to try to set up an environment with your exact set up and see if I can recreate the issue.

**Comment by dot4822** [comment]
Hi Shafferm,

I have used DRAM to annotate 944 genomes, out of which 31 genomes have got the exact error as described in #34 and #39 issues. I have already re-ran the genomes, but the error remained the same. The DRAM I am using was installed via Conda directly. I wonder whether you have already found the reseason.

Thanks!

Best regards,
Dot

**Comment by nightkid03** [comment]
> It worked on my system. [Here](https://github.com/shafferm/DRAM/files/5646298/anno.tar.gz) are the results if you want to merge this into your results. I am going to try to set up an environment with your exact set up and see if I can recreate the issue.

Thank you Shafferm, 
I installed via conda directly as @dot4822. Hope you can find the reason :)

**Comment by francis29029** [comment]
> It worked on my system. [Here](https://github.com/shafferm/DRAM/files/5646298/anno.tar.gz) are the results if you want to merge this into your results. I am going to try to set up an environment with your exact set up and see if I can recreate the issue.

Hello, I am facing similar problem with hmmer and segmentation error. I was wondering if you could share your setup ? (i.e. result of conda list ?)
