### ISSUE TITLE
How to add pathways

### ISSUE THREAD

**Issue by DennyPopp** [shafferm/DRAM#40]
Dear Michael,

thanks a lot for this great tool! I would like add a few pathways I am particularly interested in (syntrophic acetate, propionate and butyrate oxidation). I have already compiled a list of genes similar as in the _genome_summary_form.tsv_ file. However, I do not know how to proceed. It would be fine to have these specific pathways included in my local DRAM version. To have this implemented in the final _metabolism_summary.xlsx_ would be sufficient. How can I achieve this?

Thanks a lot and best regards,
Denny

**Comment by shafferm** [comment]
Hey @DennyPopp sorry for the slow reply. I have implemented a feature in the that is currently in the master branch, and will be included in the next release, where you can add a custom distillate sheet. To use this feature you can build your distillate in the same format (seems like you already got this done!) then use the flag `--custom_distillate` with a path to your custom distillate sheet. The output `metabolism_summary.xlsx` will have everything that is usually in the distillate as well as your custom modules. To get this feature right now you can install the version of DRAM from the master branch (instructions here: https://github.com/shafferm/DRAM/wiki/5.-Managing,-updating-or-moving-a-DRAM-installation-and-databases#updating-your-dram-installation) or wait till the new release comes out.

If you want to get this done right now then you can modify the `genome_summart_form.tsv` as found by running `DRAM-setup.py print_config`. Then when you distill all your custom modules will be there.

**Comment by DennyPopp** [comment]
Hey @shafferm thanks a lot for your answer! The flag `--custom_distillate` works perfect for me. It is actually very easy for me now to include own pathways. Thanks a lot!
