### ISSUE TITLE
no database available

### ISSUE THREAD

**Issue by elffairy90** [shafferm/DRAM#44]
![Un1titled](https://user-images.githubusercontent.com/49053347/98492497-05dec100-2273-11eb-9a8a-b0ff1e33435d.png)

After I set up the database for DRAM, it still says database for anything is NONE, is it right?
But there are all these files inside the DRAM_database folder

**Comment by shafferm** [comment]
That definitely isn't right! Where there any error messages when you ran `DRAM-setup.py prepare_databases`? If that ran successfully then you can get around this issue using `DRAM-setup.py set_database_locations` withthe loactions from the folder where you found the databases. You can read about doing that here: https://github.com/shafferm/DRAM/wiki/5.-Managing,-updating-or-moving-a-DRAM-installation-and-databases#moving-your-dram-databases

**Comment by mw55309** [comment]
The command I ran seemed to work, but haven't tested yet:

```sh
DRAM-setup.py set_database_locations \
 --kegg_db_loc DRAM_data/kegg.20201216.mmsdb \
 --uniref_db_loc DRAM_data/uniref90.20201216.mmsdb \
 --pfam_db_loc DRAM_data/pfam.mmspro \
 --dbcan_db_loc DRAM_data/dbCAN-HMMdb-V8.txt \
 --viral_db_loc DRAM_data/refseq_viral.20201217.mmsdb \
 --peptidase_db_loc DRAM_data/peptidases.20201217.mmsdb \
 --vogdb_db_loc DRAM_data/vog_latest_hmms.txt \
 --vog_annotations DRAM_data/vog_annotations_latest.tsv.gz \
 --kofam_hmm_loc DRAM_data/kofam_profiles.hmm \
 --kofam_ko_list_loc DRAM_data/kofam_ko_list.tsv \
 --pfam_hmm_dat DRAM_data/Pfam-A.hmm.dat.gz \
 --genome_summary_form_loc DRAM_data/genome_summary_form.20201217.tsv \
 --module_step_form_loc DRAM_data/module_step_form.20201217.tsv \
 --etc_module_database_loc DRAM_data/etc_mdoule_database.20201217.tsv \
 --function_heatmap_form_loc DRAM_data/function_heatmap_form.20201217.tsv \
 --amg_database_loc DRAM_data/amg_database.20201217.tsv \
 --description_db_loc DRAM_data/description_db.sqlite \
 --dbcan_fam_activities DRAM_data/CAZyDB.07312019.fam-activities.txt
```
