### ISSUE TITLE
: how long it take to run DRAM-setup.py prepare_databases --output_dir DRAM_data ?

### ISSUE THREAD

**Issue by francis29029** [shafferm/DRAM#46]
Hello, we are currently trying to install DRAM on a linux system with 1.05Tb memory. Last Friday (december 12) we run the following command :
DRAM-setup.py prepare_databases --output_dir DRAM_data

And here in the current output:
2020-12-10 18:17:59.657009: Database preparation started
6:08:01.950905: UniRef database processed
7:11:09.469001: PFAM database processed
7:11:29.113029: dbCAN database processed
7:11:56.204872: RefSeq viral database processed
7:12:38.211718: MEROPS database processed
7:15:08.275596: VOGdb database processed
7:24:08.214569: KOfam database processed
7:24:12.791234: KOfam ko list processed
7:24:13.243384: PFAM hmm dat processed
7:24:18.953450: dbCAN fam activities processed
7:24:22.740282: VOGdb annotations processed
7:24:25.099618: DRAM databases and forms downloaded
7:24:25.133662: Files moved to final destination
7:24:25.133894: Setting database paths
7:24:25.134566: Database locations added to CONFIG
7:24:25.436835: Database connection established
7:24:25.436890: KEGG descriptions added to description database

So from last Friday (12 of December) we are getting stuck at this stage: "KEGG descriptions added to description database" and we were wondering is something really run in the background or if the process is “blocked”. Is there is any check we could do to see if something is moving ? (we do not see any error messages)

Any suggestions are welcome

Thanks a lot

Francis

**Comment by mw55309** [comment]
I recommend looking at the size of the ```DRAM_data/description_db.sqlite``` file - if it is growing, then the process is still running

**Comment by francis29029** [comment]
Thanks ! it's a good trick
we finally sorted out (it was just a bit slow than expected)

**Comment by mw55309** [comment]
Awesome - be good to close the issue then :)
