### ISSUE TITLE
'mmseqs', 'createindex', returned non-zero exit status 1.

### ISSUE THREAD

**Issue by liupfskygre** [shafferm/DRAM#51]
Hi, Mike,
   Happy new year! Pengfei is asking:)
    I try to setup DRAM on my server, now a test running got the following error,
not sure what is happening.
thanks! 

#error track 
DRAM.py annotate -i 'GD2_bin.135.fa'  -o annotation_test_GD --min_contig_size 1000 --threads -30 --low_mem_mode
1 fastas found
2021-01-02 15:08:36.850872: Annotation started
0:00:00.005770: Retrieved database locations and descriptions
0:00:00.005808: Annotating GD2_bin.135
0:00:05.149311: Turning genes from prodigal to mmseqs2 db
Traceback (most recent call last):
  File "/home/dell/.conda/envs/DRAM/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 963, in annotate_bins_cmd
    annotate_bins(fasta_locs, output_dir, min_contig_size, prodigal_mode, trans_table, bit_score_threshold,
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 1000, in annotate_bins
    all_annotations = annotate_fastas(fasta_locs, output_dir, db_locs, db_handler, min_contig_size, prodigal_mode,
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 919, in annotate_fastas
    annotations_list.append(annotate_fasta(fasta_loc, fasta_name, fasta_dir, db_locs, db_handler, min_contig_size,
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 820, in annotate_fasta
    annotations = annotate_orfs(gene_faa, db_locs, tmp_dir, start_time, db_handler, custom_db_locs, bit_score_threshold,
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/annotate_bins.py", line 719, in annotate_orfs
    make_mmseqs_db(gene_faa, query_db, create_index=True, threads=threads, verbose=verbose)
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 49, in make_mmseqs_db
    run_process(['mmseqs', 'createindex', output_loc, tmp_dir, '--threads', str(threads)], verbose=verbose)
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/utils.py", line 38, in run_process
    return subprocess.run(command, check=check, shell=shell, stdout=subprocess.PIPE,
  File "/home/dell/.conda/envs/DRAM/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mmseqs', 'createindex', **'annotation_test_GD/working_dir/GD2_bin.135/tmp/gene.mmsdb', 'annotation_test_GD/working_dir/GD2_bin.135/tmp/tmp', '--threads', '-30']' returned non-zero exit status 1.**

#this is my db info
# i do not have uniref and kegg db
DRAM-setup.py print_config
KEGG db: None
KOfam db: /home/dell/bio_db/DRAM_data/kofam_profiles.hmm
KOfam KO list: /home/dell/bio_db/DRAM_data/kofam_ko_list.tsv
UniRef db: None
Pfam db: /home/dell/bio_db/DRAM_data/pfam.mmspro
Pfam hmm dat: /home/dell/bio_db/DRAM_data/Pfam-A.hmm.dat.gz
dbCAN db: /home/dell/bio_db/DRAM_data/dbCAN-HMMdb-V9.txt
dbCAN family activities: /home/dell/bio_db/DRAM_data/CAZyDB.07302020.fam-activities.txt
RefSeq Viral db: /home/dell/bio_db/DRAM_data/refseq_viral.20210102.mmsdb
MEROPS peptidase db: /home/dell/bio_db/DRAM_data/peptidases.20210102.mmsdb
VOGDB db: /home/dell/bio_db/DRAM_data/vog_latest_hmms.txt
VOG annotations: /home/dell/bio_db/DRAM_data/vog.annotations.tsv.gz
Description db: /home/dell/bio_db/DRAM_data/description_db.sqlite
Genome summary form: /home/dell/bio_db/DRAM_data/genome_summary_form.tsv
Module step form: /home/dell/bio_db/DRAM_data/module_step_form.tsv
ETC module database: /home/dell/bio_db/DRAM_data/etc_module_database.tsv
Function heatmap form: /home/dell/bio_db/DRAM_data/function_heatmap_form.tsv
AMG database: /home/dell/bio_db/DRAM_data/amg_database.20210102.tsv

## this is the version of mmseq2 i used 
MMseqs2 Version: 12.113e3

**Comment by mw55309** [comment]
Have you tried running the command outside of DRAM?

The commands for creating a DB and an index are available at the MMSeqs2 github: https://github.com/soedinglab/MMseqs2#search

**Comment by liupfskygre** [comment]
Hi, thanks for the reply. I just run the following command, seems working: 
mmseqs createdb J35_bin.10.fa exampledb

mmseqs createindex exampledb tmp
Database exampledb is a nucleotide database. 
Please provide the parameter --search-type 2 (translated) or 3 (nucleotide)

then I tried, 
 mmseqs createindex exampledb tmp --search-type 3
got the following 

-rw-rw-r-- 1 dell dell  831K 1月   5 21:48 exampledb
-rw-rw-r-- 1 dell dell     4 1月   5 21:48 exampledb.dbtype
-rw-rw-r-- 1 dell dell  6.7K 1月   5 21:48 exampledb_h
-rw-rw-r-- 1 dell dell     4 1月   5 21:48 exampledb_h.dbtype
-rw-rw-r-- 1 dell dell  2.1K 1月   5 21:48 exampledb_h.index
-rw-rw-r-- 1 dell dell  8.1G 1月   5 21:50 exampledb.idx
-rw-rw-r-- 1 dell dell     4 1月   5 21:50 exampledb.idx.dbtype
-rw-rw-r-- 1 dell dell   319 1月   5 21:50 exampledb.idx.index
-rw-rw-r-- 1 dell dell  2.8K 1月   5 21:48 exampledb.index
-rw-rw-r-- 1 dell dell  7.5K 1月   5 21:48 exampledb.lookup
-rw-rw-r-- 1 dell dell    16 1月   5 21:48 exampledb.source

it is working right outside dram?

**Comment by mw55309** [comment]
Yes it does seem to be working!

Can you try it on the data it failed on:

```sh
'annotation_test_GD/working_dir/GD2_bin.135/tmp/gene.mmsdb'
```

How big is that file? Can you create an index from it?

**Comment by liupfskygre** [comment]
yes,
$mmseqs createindex gene.mmsdb tmp --search-type 3
```
indexdb gene.mmsdb gene.mmsdb --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --alph-size nucl:5,aa:21 --comp-bias-corr 1 --max-seq-len 65535 --max-seqs 300 --mask 1 --mask-lower-case 0 --spaced-kmer-mode 1 -s 7.5 --k-score 0 --check-compatible 0 --search-type 3 --split 0 --split-memory-limit 0 -v 3 --threads

```

**Comment by liupfskygre** [comment]
Hi, I think I find the error, I put a '-30' to threads, which should be 30, now it is working. not the issue of mmseqs, 
mmseqs works fine. 

```
annotation_test_GD/working_dir/GD2_bin.135/tmp/tmp', '--threads', '-30'
```

**Comment by mw55309** [comment]
Awesome! Be good to close the issue :)
