### ISSUE TITLE
Help with Setting up DRAM

### ISSUE THREAD

**Issue by kiaadams2118** [shafferm/DRAM#55]
Hi all! 

Thank you so much for this resource. I have gotten to the step of setting up DRAM without access to KEGG using my MacOSX. I am doing so in a conda environment but have pip installed as well. 

When I use the command for lack of KEGG access: 

DRAM-setup.py prepare_databases --output_dir DRAM_data

I am met with 
Traceback (most recent call last):
  File "/Users/kiaadams/opt/anaconda3/envs/pandas_env/bin/DRAM-setup.py", line 5, in <module>
    from mag_annotator.database_processing import prepare_databases, set_database_paths, print_database_locations,\
  File "/Users/kiaadams/opt/anaconda3/envs/pandas_env/lib/python3.6/site-packages/mag_annotator/database_processing.py", line 9, in <module>
    import pandas as pd
  File "/Users/kiaadams/opt/anaconda3/envs/pandas_env/lib/python3.6/site-packages/pandas/__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']

I updated numpy because of a previous error. Now it says numpy is missing even though it is there. Maybe I need to use a specific version of numpy somewhere between my initial install of numpy and the updated version? 

Let me know :)

**Comment by mw55309** [comment]
The conda env already uses pip

Have you tried in a fresh conda environment and just using the environment.yaml?

**Comment by kiaadams2118** [comment]
I am new to python so still getting accustomed with some of these things.  

After looking at it more I realized I was using the same conda environment I had used to install pandas, and that certain packages were incompatible I believe. So I thought maybe I need to try setting it up as you suggest with a fresh environment! 

I will do that today.


# #

**Comment by kiaadams2118** [comment]
Thank you for the prompt response!!
