### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by ucassee** [shafferm/DRAM#57]
Hi,

I met an error when setup the database with `DRAM-setup.py prepare_databases --output_dir DRAM_data`.

`subprocess.CalledProcessError: Command '['wget', '-O', 'DRAM_data/database_files/genome_summary_form.20210118.tsv', 'https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv']' returned non-zero exit status 4.`

My server can't access this address. How can I  debug this?

Thanks

**Comment by mw55309** [comment]
I guess your server does not have web access, or perhaps web was down

Try

```sh
wget -O DRAM_data/database_files/genome_summary_form.20210118.tsv https://raw.githubusercontent.com/shafferm/DRAM/master/data/genome_summary_form.tsv
```

Does that work?

If your server can't access the web, you'll need to contact your sys/admin

**Comment by ucassee** [comment]
Hi @mw55309 , 
My server can access other webs except for https://raw.githubusercontent.com. I wonder if it is possible for you to transfer these tables to another public network address?
Thanks

**Comment by shafferm** [comment]
@ucassee this is something I am working on figuring out the best way forward for. Check out the responses given in #41. For now you can annotate with DRAM-v without virsorter but you will not get auxiliary scores. We currently don't feel comfortable standing behind calling genes potential AMGs without auxiliary scores so distilling is currently not possible without running virsorter 1.
