### ISSUE TITLE
full use of threads when doing hmmsearch during dram

### ISSUE THREAD

**Issue by liupfskygre** [shafferm/DRAM#59]
Hi, Mike,
    I am running DRAM on my server, DRAM annotation is relative slow due to hmmsearch only use 2-3 process no matter how many threads i set. is this the case or could we set hmmsearch to use more and be faster?

thanks,
Pengfei

**Comment by shafferm** [comment]
Hey Pengfei! Sorry for the super super slow reply. I've been buried in other projects for the past two months. Unfortunately the hmmsearch against VOGdb is the slowest part of the whole pipeline. If you want to skip annotating with VOGdb to speed things up you can remove it from your CONFIG file by setting `"vogdb": null`.

In future versions I am planning on changing over all HMM searches to mmseqs2 which should be faster but I need to do some benchmarking before I make that switch.
