### ISSUE TITLE
Segmentation violation error  with hmmsearch (died with <Signals.SIGSEGV: 11>)

### ISSUE THREAD

**Issue by francis29029** [shafferm/DRAM#60]
hello,

While annotating some mags I encounter this error with the hmmsearch. Does any of you already encounter this error using DRAM and could possibly help ?

ps: my dram setup work and I already annotated dataset of 350 MAGs. But sometimes, rarely, for some MAGs, I encounter this error. 

According google it's a "segmentation violation" and it's link with some memory issues....

subprocess.CalledProcessError: Command '['hmmsearch', '--domtblout', 'genomes/annotations/dram/intermediate_files/MAG130/working_dir/MAG130/tmp/kofam_profile.b6', '--cpu', '8', '/Software/python/Anaconda3-2020.11-DRAM/DRAM_data_1/kofam_profiles.hmm', 'genomes/annotations/dram/intermediate_files/MAG130/working_dir/MAG130/tmp/genes.faa']' died with <Signals.SIGSEGV: 11>.

Thanks a lot

Francis

**Comment by javadgh6** [comment]
I had the same problem. change hmmer from 3.3.1 version to 3.1b2 will solve the problem.

**Comment by francis29029** [comment]
Hello, thanks for your reply ! hum the 3.1b2 is very old version (2015) no ?

Then by searching "hmmer and segmentation fault", I was able to find out other similar issues ? (which I did not find the first time):
https://github.com/shafferm/DRAM/issues/34
https://github.com/shafferm/DRAM/issues/39

and now I do not know if there is really a solution to this segmentation fault (seems it depends of the system). We are using the hmmer 3.3.1 version. Does upating to 3.3.2 (last release might solved the issue ?)

here is the output of conda  list
# packages in environment at /nihs/Software/python/Anaconda3-2020.11-DRAM/envs/DRAM:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
altair                    4.1.0                      py_1    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
barrnap                   0.9                           3    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
brotlipy                  0.7.0           py39h38d8fee_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachecontrol              0.12.6                     py_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_0    conda-forge
cffi                      1.14.4           py39he32792d_1    conda-forge
chardet                   3.0.4           py39h079e4ff_1008    conda-forge
cryptography              3.2.1            py39h01d1d65_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py39hfbd4741_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
dram-bio                  1.1.1                     dev_0    <develop>
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
gawk                      5.1.0                h516909a_0    conda-forge
gdbm                      1.18                 h0a1914f_2    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
git                       2.29.2          pl5320h78be0e9_1    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
hdmedians                 0.14.1           py39h1dff97c_1    conda-forge
hmmer                     3.3.1                he1b5a44_0    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.1.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        3.1.1                hd8ed1ab_0    conda-forge
infernal                  1.1.3                h516909a_0    bioconda
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   7.19.0           py39hef51801_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py39hf3d152e_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
kiwisolver                1.3.1            py39h081fc7a_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.0                h516909a_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h4f3a223_6    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
lockfile                  0.12.2                     py_1    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py39h38d8fee_2    conda-forge
matplotlib-base           3.3.3            py39h98787fa_0    conda-forge
mmseqs2                   12.113e3             h2d02072_2    bioconda
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.0            py39h081fc7a_2    conda-forge
natsort                   7.1.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.4           py39h57d35e7_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openpyxl                  3.0.5                      py_0    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.7               pyhd3deb0d_0    conda-forge
pandas                    1.1.5            py39hde0f152_0    conda-forge
parallel                  20201122             ha770c72_0    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py39h397ff4d_0    conda-forge
pip                       20.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py39h079e4ff_3    conda-forge
prodigal                  2.6.3                h516909a_2    bioconda
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py39hbd71b63_1    conda-forge
pysocks                   1.7.1            py39h079e4ff_2    conda-forge
pytest                    6.1.2            py39hf3d152e_0    conda-forge
python                    3.9.1           hffdb5ce_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruby                      2.7.2                he592edb_3    conda-forge
scikit-bio                0.5.6            py39h16ac069_4    conda-forge
scikit-learn              0.23.2           py39hf3c863f_3    conda-forge
scipy                     1.5.3            py39hee8e79c_0    conda-forge
setuptools                49.6.0           py39h079e4ff_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.20           py39h07f9747_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py39hbd71b63_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
trnascan-se               2.0.7           pl526h516909a_0    bioconda
tzdata                    2020d                h516909a_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wget                      1.20.1               h22169c7_0    conda-forge
wheel                     0.36.1             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Comment by shafferm** [comment]
Looks like this has been fixed. Sorry for missing your issue earlier but glad it got figured out!
