### ISSUE TITLE
TypeError in DRAM-v.py distill

### ISSUE THREAD

**Issue by Camaika** [shafferm/DRAM#61]
Hey there!

I am running this command on the file added to this issue:
`DRAM-v.py distill -i ./all_annotations_merged_except_1_failed_contig/annotations.tsv -o ./all_annotations_merged_except_1_failed_contig/distilled/`

and I get this error message:
sys:1: DtypeWarning: Columns (31) have mixed types.Specify dtype option on import or set low_memory=False.
0:00:00.821167: Retrieved database locations and descriptions
0:00:10.784795: Determined potential amgs
Traceback (most recent call last):
  File "/home/sunam157/.conda/envs/DRAM/bin/DRAM-v.py", line 140, in <module>
    args.func(**args_dict)
  File "/home/sunam157/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/summarize_vgfs.py", line 240, in summarize_vgfs
    viral_genome_stats = make_viral_stats_table(annotations, potential_amgs, groupby_column)
  File "/home/sunam157/.conda/envs/DRAM/lib/python3.9/site-packages/mag_annotator/summarize_vgfs.py", line 89, in make_viral_stats_table
    virus_transposase_present = sum(frame.is_transposon) > 0  # transposase on contig
TypeError: unsupported operand type(s) for +: 'int' and 'str'

I don't know, if it is important, but the annotations.tsv is from two merged runs. I merged the two files with:

import pandas as pd

annotations1 = pd.read_table("/work_dagan/sunam157/OMZ/DRAM-v/all_annotations_merged_except_1_failed_contig/a1/annotations.tsv", sep='\t', index_col=0)
annotations2 = pd.read_table("/work_dagan/sunam157/OMZ/DRAM-v/all_annotations_merged_except_1_failed_contig/a2/annotations.tsv", sep='\t', index_col=0)
merged_annotations = pd.concat([annotations1, annotations2])
merged_annotations.to_csv("/work_dagan/sunam157/OMZ/DRAM-v/all_annotations_merged_except_1_failed_contig/annotations.tsv", sep='\t')

[annotations.zip](https://github.com/shafferm/DRAM/files/5942996/annotations.zip)

**Comment by shafferm** [comment]
Thanks so much for providing your annotations file. Those are the right commands to merge annotations fils. What is causing this issue is the fact that you have some blanks, some `True` and some `False` in the `is_transposon` column. If you annotate with DRAM-v all those should have a `True` or `False`.

Did you merge annotations where some were annotated where you provided the virsorter affi contigs file? Or were some of these annotated with DRAM and some with DRAM-v?

**Comment by Camaika** [comment]
Thank you for your reply!
They were all annotated with DRAM-v with the affi contigs file provided. All from the same virsorter and DRAM-v annotate run. The annotation just failed and for one contig, so I excluded it and ran the annotation for the remaining contigs. After that, I merged both runs and tried to distill.

**Comment by shafferm** [comment]
Okay that means the first round of annotation didn't get the last few steps of adding the DRAM-v columns. I have a script to add those separately that you can use. Then you will need to merge again and then running distill should work.

The command to run it is:
```python
python add_dramv_scores_and_flags.py -i ./virsorter2_1/for-dramv/final-viral-combined-for-dramv.fa -a ./annotation1/annotations.tsv -o ./annotation1/annotations_w_dramv.tsv -v ./virsorter2_1/for-dramv/viral-affi-contigs-for-dramv.tab 
```

Or similar with updated paths. I just took these from your previous message so these might need to be replaced.

https://gist.github.com/shafferm/96183f0ab54d21173668075f64002d77

**Comment by Camaika** [comment]
Thank you for your help, it worked!!! I get some ' "No distillate information found for gene %s" % gene' warnings, but I guess that's normal. So thank you very much!

**Comment by shafferm** [comment]
Those are totally normal. It happens when a gene is found that is a known AMG but also is not in our distillate metabolism database.
