### ISSUE TITLE
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 1283, saw 7

### ISSUE THREAD

**Issue by liupfskygre** [shafferm/DRAM#69]
Hi, Mike,
     After annotation,  I am trying to do distill
```
DRAM.py distill -i ./annotations.tsv -o genome_summaries --trna_path ./trnas.tsv --rrna_path ./rrnas.tsv
```
got this error, not occur before

not sure what's going wrong. 

thanks.

Pengfei

**Comment by shafferm** [comment]
Hi Pengfei,

Can you post the full output with the entire error? Seeing what line 1283 of your annotations file could help too. You can use this command `sed '1283q;d'`.

Mike

**Comment by liupfskygre** [comment]
Hi, Mike,
    thanks for your reply; I am moving to my new university so not access to the my server, but have incomplete install of DRAM. now on server everything is great. 

Best,
Pengfei

**Comment by shafferm** [comment]
That's good to hear. Let me know if you have any more issues!
