### ISSUE TITLE
How to extract gene within hydrocarbon degradation category?

### ISSUE THREAD

**Issue by nduan1** [shafferm/DRAM#79]
Hi Dr. Schaffer,

I am trying to use the command below to extract genes within hydrocarbon degradation found in annotations.tsv
DRAM.py strainer -i /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/dram_mag_gene/contigs.nonvirus/M107_annotation/annotations.tsv \
-f /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/dram_mag_gene/contigs.nonvirus/M107_annotation/genes.fna \
-o /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/dram_mag_gene/contigs.nonvirus/M107_annotation/genes.hydrocarbon.fna \
--categories Hydrocarbon degradation 
or --categories hydrocarbon degradation 
or --categories Hydrocarbon Degradation 

It didn't work, and give me the error 
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/conda2/envs/DRAM-new/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/lustre/haven/proj/UTK0124/conda2/envs/DRAM-new/lib/python3.9/site-packages/mag_annotator/pull_sequences.py", line 30, in pull_sequences
    raise ValueError("Categories or identifiers provided yielded no annotations")
ValueError: Categories or identifiers provided yielded no annotations
virus/M107_annotation/annotations.tsv \-i /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/dram_mag_gene/contigs.non 
> -f /lustre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/dram_mag_gene/contigs.nonvirus/M107_annotation/genes.fna \
on.fna \stre/haven/proj/UTK0124/ningd/whole_metagenome_2020/dram/dram_mag_gene/contigs.nonvirus/M107_annotation/genes.hydrocarb 
> --categories Hydrocarbon degradation
Traceback (most recent call last):
  File "/lustre/haven/proj/UTK0124/conda2/envs/DRAM-new/bin/DRAM.py", line 145, in <module>
    args.func(**args_dict)
  File "/lustre/haven/proj/UTK0124/conda2/envs/DRAM-new/lib/python3.9/site-packages/mag_annotator/pull_sequences.py", line 30, in pull_sequences
    raise ValueError("Categories or identifiers provided yielded no annotations")
ValueError: Categories or identifiers provided yielded no annotations

Could you help me with this?

Thanks!

Ning

**Comment by shafferm** [comment]
Hey Ning,

I think you need to put quotes around it since there is a space. Try using "hydrocarbon degradation" and then let me know if that works!

Thanks,

Mike

**Comment by nduan1** [comment]
It works! Thank you Dr. Schaffer!

Best,

Ning
