### ISSUE TITLE
Instructions in one place only

### ISSUE THREAD

**Issue by bph6212ln** [shafferm/DRAM#8]
The installation and setup instructions in the wiki are not the same as the instructions in the README.md file. The wrong or outdated version should be removed and replaced with a reference pointing to the other.

For example, this is from the wiki: (paraphrased)

> I have access to KEGG
> Then set up DRAM using the following command:
> DRAM-setup.py prepare_databases --output_dir DRAM_data --kegg_loc kegg.pep
> 
> I don't have access to KEGG
> Not a problem. Then use this command:
> DRAM-setup.py prepare_databases --output_dir DRAM_data --kegg_loc kegg.pep

...it's the same command. The README.md file seems to have the correct commands.

Conversely, the README.md file mentions nothing about being able to `pip install DRAM_bio` but instead advocates using pip install in "develop mode" against a checked out copy of the repo which creates a dependency on the source files, (which isn't suitable in a multi-user environment if not planned for ahead of time).

**Comment by shafferm** [comment]
Thanks for these comments. I have updated both the wiki and the README.md to better synchronize their content.

We will be keeping the instructions in both the README.md and the wiki as README.md acts as a quickstart guide for users while the wiki gives more in depth information. We will try to do a better job keeping their content more inline in the future.
