### ISSUE TITLE
UserWarning: No rRNAs were detected, no rrnas.tsv file will be created?

### ISSUE THREAD

**Issue by gruningerrj** [shafferm/DRAM#83]
Hi again. 
DRAM has been running overnight and all of the mags that has been annotated so far have been showing the warning "UserWarning: No rRNAs were detected, no rrnas.tsv file will be created". I am not sure if this is just an issue around the db's that were installed? This seems strange that all of them would not have rRNAs but I am not sure what to make of the warning.

Thanks
Rob

**Comment by shafferm** [comment]
This warning is given out per genome. So the number of times you see it is equivalent to the number of genomes without an `rrnas.tsv` file and therefore no annotated rRNAs. No seeing rRNAs in a MAG isn't uncommon because of the difficulties associated both assembling and binning rRNA sequences.
