### ISSUE TITLE
genome cartoon

### ISSUE THREAD

**Issue by ankit4035** [shafferm/DRAM#96]
Hello,
I really liked your tool and am currently setting up to use for some of my MAGs. 

I also attended your session in recent World Microbe Forum and wanted to ask how did you prepared the genome cartoons that were included in the presentation?

Thank you

Ankit

**Comment by shafferm** [comment]
Hi Anki,

The genome cartoons from the World Microbe Forum talk were built by Mikayla Borton. She makes them in Adobe Illustrator. If you want more detail on how we turn annotations into a genome cartoon you can check out the workshop we lead as part of the Ohio State University CoMS webinar. The video is on youtube (https://www.youtube.com/watch?v=9xH7-UwHqMQ) and the resources to follow the workshop activities are here https://u.osu.edu/coms/webinar-resources/.

Mike

**Comment by ankit4035** [comment]
Thanks for the links..
